### ISSUE TITLE
Operator doesn't load the cloned repository correctly

### ISSUE THREAD

**Issue by amirrmonfared** [presslabs/wordpress-operator#113]
**What happened**:
When we deploy a wp instance with the order to clone the codes including wp-content no matter if we define the bootstrap env or not it will be redirected to the address `http://mydomain.wordpress-websites.svc/wp/wp-admin/install.php` and if I correct it to `mydomain.com/wp/wp-admin/install.php` the installation page won't load correctly just with HTML and also if I install it the site will be broken. 

I tried with a fresh instance and installed themes and plugins it was fine and I downloaded the content and configs from the fresh instance which was working to produce another instance with a predefined config and content it didn't work again.

**What you expected to happen**:
To have the plugin and themes already installed and not be broken when the operator clones it.

**How to reproduce it (as minimally and precisely as possible)**:
you can use this config, the git repo is also public so you can use it. 

```

---
apiVersion: v1
kind: Secret
metadata:
  name: mysite-db
  namespace: wordpress-websites
type: Opaque
data:
  ROOT_PASSWORD: MTIzNDU=
  USER: QWRtaW4=
  PASSWORD: MTIzNA==
  DATABASE: bXlzaXRl
---
apiVersion: v1
kind: Secret
metadata:
  name: mysite-salt
  namespace: wordpress-websites
type: Opaque
data:
  AUTH_KEY: 
  SECURE_AUTH_KEY: 
  LOGGED_IN_KEY: 
  NONCE_KEY: 
  AUTH_SALT: 
  SECURE_AUTH_SALT: 
  LOGGED_IN_SALT: 
  NONCE_SALT: 
---
kind: Secret
apiVersion: v1
metadata:
  name: mysite
  namespace: wordpress-websites
data:
  EMAIL: YWRtaW5AZ21haWwuY29t
  PASSWORD: MTIzNDU=
  TITLE: bXlzaXRl
  USER: YWRtaW4=
type: Opaque
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: mysite
  namespace: wordpress-websites
spec:
  replicas: 1
  secretName: mysite-db
---
apiVersion: wordpress.presslabs.org/v1alpha1
kind: Wordpress
metadata:
  name: mysite
  namespace: wordpress-websites
spec:
  replicas: 1
  code:
    git:
      repository: https://github.com/amirrmonfared/testmava.git
      reference: main
  image: docker.io/bitpoke/wordpress-runtime:6.3.1
  imagePullPolicy: Always
  wordpressPathPrefix: /wp
  env:
    - name: DB_HOST
      value: mysite-mysql-master
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: mysite-db
          key: USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysite-db
          key: PASSWORD
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: mysite-db
          key: DATABASE
    - name: WORDPRESS_BOOTSTRAP_USER
      valueFrom:
        secretKeyRef:
          key: USER
          name: mysite
    - name: WORDPRESS_BOOTSTRAP_PASSWORD
      valueFrom:
        secretKeyRef:
          key: PASSWORD
          name: mysite
    - name: WORDPRESS_BOOTSTRAP_EMAIL
      valueFrom:
        secretKeyRef:
          key: EMAIL
          name: mysite
    - name: WORDPRESS_BOOTSTRAP_TITLE
      valueFrom:
        secretKeyRef:
          key: TITLE
          name: mysite
```

**Anything else?**:
