### ISSUE TITLE
Unable to start site when configure code.git options

### ISSUE THREAD

**Issue by esteban1983cl** [presslabs/wordpress-operator#62]
**What happened**:
Unable to star pod with site
**What you expected to happen**:
Clone the code
**How to reproduce it (as minimally and precisely as possible)**:
Config git.code options like this
```yaml
code: # where to find the code
    # contentSubpath: .
    # by default, code get's an empty dir. Can be one of the following:
    git:
      repository: xxxxxxx
      reference: master
      env:
      - name: SSH_RSA_PRIVATE_KEY
        valueFrom:
          secretKeyRef:
            name: eurofashion-ecommerce-deploy-key
            key: id_rsa
```
**Anything else?**:
Yes, prepare volumes init container is failing
```yaml
Init Containers:
  prepare-volumes:
    Container ID:  docker://42700a0ec66501d77f1aa8ecfd03ea946034606083cba60b3579b7bac93802cc
    Image:         gcr.io/google-containers/busybox@sha256:545e6a6310a27636260920bc07b994a299b6708a1b26910cfefd335fdfb60d2b
    Image ID:      docker-pullable://gcr.io/google-containers/busybox@sha256:545e6a6310a27636260920bc07b994a299b6708a1b26910cfefd335fdfb60d2b
    Port:          <none>
    Host Port:     <none>
    Args:
      /bin/sh
      -c
      #!/bin/sh
      test -d /mnt/code && chown 33:33 /mnt/code
      test -d /mnt/media && chown 33:33 /mnt/media

    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 13 Feb 2020 19:06:38 -0300
      Finished:     Thu, 13 Feb 2020 19:06:38 -0300
    Ready:          False
    Restart Count:  1
    Environment:    <none>
    Mounts:
      /mnt/code from code (rw,path="wp-content")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tctxh (ro)
```
