### ISSUE TITLE
Wordpress not in ready state

### ISSUE THREAD

**Issue by iogrids** [presslabs/wordpress-operator#90]
I tried to install wordpress using the below yaml file, but the wordpress pods are running but not in ready state. 

I have installed the wordpress operator

Is something wrong here?

wordpress.yaml file

```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "wordpress"
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress 
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80 
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db
type: Opaque
data:
  ROOT_PASSWORD: Y2hhbmdtZQ==
  USER: cm9vdA==
  PASSWORD: Y2hhbmdtZQ==
  DATABASE: d29yZHByZXNz
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-salt
type: Opaque
data:
  AUTH_KEY: KnN8Ly43KU15VDRmcipfQDNDYmhKMjF2IV5hOn
  SECURE_AUTH_KEY: LXtgKjlmPkZwfXxGX3ogYE00WUZAU3RaJHVoTVoqJVFFKFsjPSFUK2VoVXJFOw==
  LOGGED_IN_KEY: VilvQDBRNy5tM1pYaEh0cU9Yd2h+pOjpKaVNBaXwzOk9eZiU4IA==
  NONCE_KEY: OUVML0dNX35hcnFHdUsweVYxLUTlkaXFJT0FIOSYubmtLUig4fA==
  AUTH_SALT: K1ZBJGw2c3QyOENbR35PVi14aFAgOG8sVBMMHkrQW9lbg==
  SECURE_AUTH_SALT: MF5DMUdxVV9LdCpSbXw2XWM1STs5ek3PmxrdFAgcnlpJXIjSA==
  LOGGED_IN_SALT: TGx2Y2BjU1UvV3AqNFFRLkBKVWxUdEw+dCs1fENjYjVpcA==
  NONCE_SALT: NHBxSTR4U2dTe1FlX00vXTZnNk9RX03WXQ7ZiZoQQ==

---

apiVersion: wordpress.presslabs.org/v1alpha1
kind: Wordpress
metadata:
  name: wordpress
spec:
  replicas: 1
  image: quay.io/presslabs/wordpress-runtime:5.5.1-php-7.4-fix-bedrock-php-8.0  
  envFrom:
    - prefix: "WORDPRESS_"
      secretRef:
        name: wordpress-salt
  env:
    - name: DB_HOST
      value: mycluster-mysql.default.svc.cluster.local
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: wordpress-db
          key: USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: wordpress-db
          key: PASSWORD
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: wordpress-db
          key: DATABASE
  domains:
    - example.com


```
